version: '3.1'
services:
  vcontrold:
    build: .
    container_name: vcontrold
    restart: unless-stopped
    devices:
      - /dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0:/dev/vitocal:rwm
      - /dev/bus/usb:/dev/bus/usb:rwm
    environment:
      MQTTHOST: ${MQTTHOST}
      MQTTPORT: ${MQTTPORT}
      MQTTTOPIC: ${MQTTTOPIC}
      MQTTPASSWORD: ${MQTTPASSWORD}
      MQTTACTIVE: ${MQTTACTIVE}
      MQTTUSER: ${MQTTUSER}
      INTERVAL: ${INTERVAL}
      COMMANDS: ${COMMANDS}
    volumes:
      - ./config:/config
    ports:
      - 3002:3002
