version: '3.1'
services:
  vcontrold:
    build:
      context: .
      args:
        - BUILD_ARCH=amd64
        - S6_OVERLAY_VERSION=3.1.5.0
        - VCONTROLD_VERSION=master
    container_name: vcontrold
    restart: unless-stopped
    devices:
      - /dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0:/dev/vitocal:rwm
      - /dev/bus/usb:/dev/bus/usb:rwm
    environment:
      MQTT_ACTIVE: ${MQTT_ACTIVE}
      MQTT_HOST: ${MQTT_HOST}
      MQTT_PORT: ${MQTT_PORT}
      MQTT_TOPIC: ${MQTT_TOPIC}
      MQTT_USER: ${MQTT_USER}
      MQTT_PASSWORD: ${MQTT_PASSWORD}
      MQTT_INITIAL_PUB_SLEEP: ${MQTT_INITIAL_PUB_SLEEP}
      MQTT_PUB_SLEEP: ${MQTT_PUB_SLEEP}
      MQTT_SUB_SLEEP: ${MQTT_SUB_SLEEP}
    volumes:
      - ./config:/config
    ports:
      - 3002:3002
